//! Hooks — `impl Hooks for User { ... }` lifecycle callbacks, driven through the
//! hook-aware instance methods `PgModel::insert`/`save`/`destroy`.
//!
//! Requires a live PostgreSQL database:
//!
//! ```sh
//! DATABASE_URL=postgres://user:pass@localhost/rok_fluent_db \
//!   cargo run --example 11_hooks --features postgres,active
//! ```
//!
//! # Why PostgreSQL-only
//!
//! `Hooks::insert`/`save`/`destroy` are default methods on
//! [`PgModel`](rok_fluent::orm::postgres::model::PgModel), which — like the rest of the
//! Active Record layer covered in `examples/01_quickstart.rs`'s module doc — only has an
//! executor for PostgreSQL today. `ModelValues::to_values()` (generated by
//! `#[derive(Model)]`) is backend-agnostic, but the hook-aware writes that consume it are
//! not, so this example requires a live PostgreSQL database.

use rok_fluent::core::model::Model;
use rok_fluent::orm::hooks::{Hooks, OrmError, OrmResult};
use rok_fluent::orm::postgres::model::PgModel;
use rok_fluent::ModelDerive;

#[derive(Debug, Clone, sqlx::FromRow, ModelDerive)]
#[model(table = "users")]
pub struct User {
    pub id: i64,
    pub email: String,
    pub name: String,
}

impl Hooks for User {
    fn before_create(&mut self) -> OrmResult<()> {
        println!("before_create: {}", self.email);
        Ok(())
    }

    fn after_create(&self) {
        println!("after_create: id={}", self.id);
    }

    fn before_update(&mut self, dirty: &[&str]) -> OrmResult<()> {
        // This crate has no dirty-tracking, so `dirty` is always `User::columns()`.
        println!("before_update: columns considered dirty = {dirty:?}");
        Ok(())
    }

    fn after_update(&self) {
        println!("after_update: id={}", self.id);
    }

    fn before_save(&mut self) -> OrmResult<()> {
        if self.email.trim().is_empty() {
            return Err(OrmError::new("email cannot be empty"));
        }
        self.email = self.email.to_lowercase();
        Ok(())
    }

    fn after_save(&self) {
        println!("after_save: id={} email={}", self.id, self.email);
    }

    fn before_delete(&self) -> OrmResult<()> {
        println!("before_delete: id={}", self.id);
        Ok(())
    }

    fn after_delete(&self) {
        println!("after_delete: id={}", self.id);
    }
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let database_url = std::env::var("DATABASE_URL")
        .unwrap_or_else(|_| "postgres://postgres:postgres@localhost:5432/rok_fluent_db".into());
    let pool = sqlx::PgPool::connect(&database_url).await?;

    sqlx::query("DROP TABLE IF EXISTS users")
        .execute(&pool)
        .await?;
    sqlx::query(
        "CREATE TABLE users (
            id    BIGSERIAL PRIMARY KEY,
            email TEXT NOT NULL,
            name  TEXT NOT NULL
        )",
    )
    .execute(&pool)
    .await?;

    // ── insert(): before_create → before_save → INSERT → after_create → after_save ──
    let mut user = User {
        id: 0,
        email: "Ada@Example.com".into(),
        name: "Ada Lovelace".into(),
    };
    user.insert(&pool).await?;

    let inserted: User = User::find_by_pk(&pool, 1_i64)
        .await?
        .ok_or("row not found after insert")?;
    println!("\nStored row: {inserted:?}");
    assert_eq!(inserted.email, "ada@example.com"); // lowercased by before_save

    // ── save(): before_update → before_save → UPDATE by pk → after_update → after_save
    let mut to_update = inserted;
    to_update.email = "Ada.Lovelace@Example.com".into();
    to_update.save(&pool).await?;

    let updated: User = User::find_by_pk(&pool, to_update.id)
        .await?
        .ok_or("row not found after save")?;
    println!("\nUpdated row: {updated:?}");

    // before_save rejecting an invalid write — insert() aborts without touching the DB.
    let mut invalid = User {
        id: 0,
        email: "   ".into(),
        name: "Nobody".into(),
    };
    match invalid.insert(&pool).await {
        Ok(_) => println!("\nunexpected: empty-email insert succeeded"),
        Err(e) => println!("\nRejected by before_save as expected: {e}"),
    }

    // ── destroy(): before_delete → DELETE by pk → after_delete ─────────────────────
    let affected = updated.destroy(&pool).await?;
    println!("\ndestroy() removed {affected} row(s)");

    let gone = User::find_by_pk(&pool, updated.id).await?;
    println!("Row after destroy: {gone:?}");

    Ok(())
}
