[package]
name        = "rok-fluent-macros"
version.workspace    = true
edition.workspace    = true
license.workspace    = true
authors.workspace    = true
repository.workspace = true
homepage.workspace   = true
description = "Procedural macros for rok-fluent (Model, Table, Resource, Seed derives)"
keywords    = ["orm", "macro", "derive", "rok", "sqlx"]
categories  = ["database"]
rust-version = "1.85"
exclude     = ["target/"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lib]
proc-macro = true

[dependencies]
syn         = { workspace = true }
quote       = { workspace = true }
proc-macro2 = { workspace = true }
heck        = { workspace = true }
